# Generated by Django 4.2.29 on 2026-03-10 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_department_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="line_manager",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_department",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
