# Generated by Django

from django.db import migrations


HR_DEPARTMENT_NAME = "Human Resources (HR)"


def seed_hr_department(apps, schema_editor):
    Department = apps.get_model("accounts", "Department")
    Department.objects.get_or_create(
        name=HR_DEPARTMENT_NAME,
        defaults={"description": "Default department for Human Resources staff."},
    )


def reverse_seed_hr_department(apps, schema_editor):
    """No-op reverse: do not delete HR department as it may have members."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_date_of_birth_user_gender"),
    ]

    operations = [
        migrations.RunPython(seed_hr_department, reverse_seed_hr_department),
    ]
