# Generated by Django 4.2.29 on 2026-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_unit_and_supervisor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("LINE_MANAGER", "Line Manager"),
                    ("HR", "HR"),
                    ("EXECUTIVE_DIRECTOR", "Executive Director"),
                    ("MANAGING_DIRECTOR", "Managing Director"),
                    ("SUPERVISOR", "Supervisor"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
