# Generated by Django 4.2.29 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_team_and_team_lead_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("LINE_MANAGER", "Line Manager"),
                    ("HR", "HR"),
                    ("EXECUTIVE_DIRECTOR", "Executive Director"),
                    ("MANAGING_DIRECTOR", "Managing Director"),
                    ("SUPERVISOR", "Supervisor"),
                    ("TEAM_LEAD", "Team Lead"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]

