# Generated by Django 4.2.29 on 2026-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_management_department_and_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="other_names",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
