# Generated by Django 4.2.29 on 2026-03-10 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leave", "0002_seed_leave_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="cover_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="covering_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
