# Generated by Django 4.2.29 on 2026-07-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0010_leave_request_manager_approver_is_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="department_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 24h-before-start department reminder email was sent.",
                null=True,
            ),
        ),
    ]
