# Generated by Django 4.2.29 on 2026-08-14 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('leave', '0016_leave_sprint3_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='carried_forward_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of allocated_days that originated as carry-forward from the prior year.', max_digits=8),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carry_forward_expires_on',
            field=models.DateField(blank=True, help_text='When carried_forward_days expire. Null if none or already expired.', null=True),
        ),
        migrations.AddField(
            model_name='leavebalancetransaction',
            name='delta_allocated_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Change applied to allocated_days (positive = accrual/carry-forward, negative = expiry).', max_digits=8),
        ),
        migrations.AddField(
            model_name='leavebalancetransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Stable key so Beat/jobs can re-run without double-crediting.', max_length=191, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='accrual_method',
            field=models.CharField(choices=[('UPFRONT', 'Upfront (annual lump sum)'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('ANNIVERSARY', 'Employment anniversary')], default='UPFRONT', help_text='When entitlement is credited: lump sum, monthly, weekly, or anniversary.', max_length=16),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='accrual_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Days credited per accrual interval. Null = annual_entitlement divided by intervals.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='carry_forward_expiry_months',
            field=models.PositiveIntegerField(blank=True, help_text='Carried days expire this many months after the new leave year starts. Null = no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='carry_forward_max_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cap on days carried into the next year. Null = no cap.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='forfeit_unused',
            field=models.BooleanField(default=True, help_text='When carry-forward is disabled, unused days are expired at year-end.'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='prorate_new_joiners',
            field=models.BooleanField(default=False, help_text='When True, first-year entitlement is reduced by remaining calendar days in the leave year.'),
        ),
        migrations.AlterField(
            model_name='leavebalancetransaction',
            name='source',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('RECONCILE', 'Reconcile'), ('CANCEL_REFUND', 'Cancel refund'), ('RECONCILE_EDIT', 'Reconcile edit'), ('HR_ADJUST', 'HR adjust'), ('SUBMIT', 'Submit'), ('REJECT_RELEASE', 'Reject release'), ('CANCEL_RELEASE', 'Cancel release'), ('ACCRUAL_JOB', 'Accrual job'), ('YEAR_ROLLOVER', 'Year rollover'), ('EXPIRY_JOB', 'Expiry job'), ('TERMINATION', 'Termination')], max_length=24),
        ),
        migrations.AlterField(
            model_name='leavebalancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEDUCT', 'Deduct'), ('REFUND', 'Refund'), ('ADJUST', 'Adjust'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('ACCRUAL', 'Accrual'), ('CARRY_FORWARD', 'Carry-forward'), ('EXPIRY', 'Expiry'), ('FORFEIT', 'Forfeit')], max_length=16),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='carry_forward',
            field=models.BooleanField(default=False, help_text='When True, unused days may roll into the next leave year (carry_forward_allowed).'),
        ),
    ]
