# Generated by Django 4.2.29 on 2026-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0020_leave_sprint7_hr_ops"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="approverdelegate",
            new_name="leave_appro_user_id_91057a_idx",
            old_name="leave_appro_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="leavebalancetransaction",
            new_name="leave_leave_leave_r_7d27d2_idx",
            old_name="leave_leave_leave_r_8f0a1b_idx",
        ),
        migrations.RenameIndex(
            model_name="leavebalancetransaction",
            new_name="leave_leave_leave_b_1b27ca_idx",
            old_name="leave_leave_leave_b_2c4d3e_idx",
        ),
        migrations.RenameIndex(
            model_name="leavepolicy",
            new_name="leave_leave_leave_t_5da999_idx",
            old_name="leave_leave_leave_t_status_idx",
        ),
        migrations.RenameIndex(
            model_name="leavepolicyassignment",
            new_name="leave_leave_scope_t_88afc2_idx",
            old_name="leave_leave_scope_t_8a1c21_idx",
        ),
        migrations.RenameIndex(
            model_name="leavepolicyassignment",
            new_name="leave_leave_policy__8a3f05_idx",
            old_name="leave_leave_policy__b2e4f0_idx",
        ),
        migrations.RenameIndex(
            model_name="leavepolicyassignment",
            new_name="leave_leave_employe_2bc9a1_idx",
            old_name="leave_leave_employe_c3d901_idx",
        ),
        migrations.RenameIndex(
            model_name="leavesettingsauditlog",
            new_name="leave_leave_object__019ebf_idx",
            old_name="leave_leave_object__audit_idx",
        ),
        migrations.AlterField(
            model_name="leavepolicy",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
    ]
