# Generated by Django 4.2.29 on 2026-05-19 08:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, help_text='Computed on approval.', max_digits=12, null=True)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HR', 'Pending HR'), ('PENDING_ED', 'Pending Executive Director'), ('PENDING_MD', 'Pending Managing Director'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('LIQUIDATED', 'Liquidated')], default='DRAFT', max_length=20)),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resignation_deducted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DISBURSE', 'Disburse'), ('LIQUIDATE', 'Liquidate'), ('CLOSE', 'Close')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_HR', 'Pending HR'), ('PENDING_ED', 'Pending Executive Director'), ('PENDING_MD', 'Pending Managing Director'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('LIQUIDATED', 'Liquidated')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_HR', 'Pending HR'), ('PENDING_ED', 'Pending Executive Director'), ('PENDING_MD', 'Pending Managing Director'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('LIQUIDATED', 'Liquidated')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='loan.loanapplication')),
            ],
            options={
                'verbose_name': 'Loan Approval Log',
                'verbose_name_plural': 'Loan Approval Logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loan.loantype'),
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField(help_text='Calculated from disbursed_at month.')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loan.loanapplication')),
            ],
            options={
                'verbose_name': 'Loan Repayment Schedule Entry',
                'verbose_name_plural': 'Loan Repayment Schedule Entries',
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
