# Generated by Django 4.2.29 on 2026-06-18 12:18

from django.db import migrations, models
import django.db.models.deletion


def seed_loan_settings(apps, schema_editor):
    LoanSettings = apps.get_model("loan", "LoanSettings")
    LoanSettings.objects.get_or_create(
        pk=1,
        defaults={"require_line_manager_approval": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_personnel_fields"),
        ("loan", "0003_loanrepaymentschedule_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="manager_approver_is_management",
            field=models.BooleanField(
                default=False,
                help_text="If True, the PENDING_MANAGER approver is Management department line manager.",
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_MANAGER", "Pending Line Manager"),
                    ("PENDING_HR", "Pending HR"),
                    ("PENDING_ED", "Pending Executive Director"),
                    ("PENDING_MD", "Pending Managing Director"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("LIQUIDATED", "Liquidated"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loanapprovallog",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_MANAGER", "Pending Line Manager"),
                    ("PENDING_HR", "Pending HR"),
                    ("PENDING_ED", "Pending Executive Director"),
                    ("PENDING_MD", "Pending Managing Director"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("LIQUIDATED", "Liquidated"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loanapprovallog",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_MANAGER", "Pending Line Manager"),
                    ("PENDING_HR", "Pending HR"),
                    ("PENDING_ED", "Pending Executive Director"),
                    ("PENDING_MD", "Pending Managing Director"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("LIQUIDATED", "Liquidated"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LoanSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_line_manager_approval", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observer_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.department",
                    ),
                ),
                (
                    "observer_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan settings",
                "verbose_name_plural": "Loan settings",
            },
        ),
        migrations.RunPython(seed_loan_settings, migrations.RunPython.noop),
    ]
