# Generated by Django 4.2.29 on 2026-03-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_a972ce_idx",
            old_name="notificatio_recipient_7a1db0_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_564b1f_idx",
            old_name="notificatio_recipient_7b3bb8_idx",
        ),
    ]
