# Generated by Django 4.2.29 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_rename_notificatio_recipient_7a1db0_idx_notificatio_recipie_a972ce_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("LEAVE_SUBMITTED", "Leave submitted"),
                    ("LEAVE_ACTION_REQUIRED", "Leave action required"),
                    ("LEAVE_APPROVED", "Leave approved"),
                    ("LEAVE_REJECTED", "Leave rejected"),
                    ("LOAN_SUBMITTED", "Loan submitted"),
                    ("LOAN_APPROVED", "Loan approved"),
                    ("LOAN_REJECTED", "Loan rejected"),
                    ("LOAN_DISBURSED", "Loan disbursed"),
                    ("LOAN_LIQUIDATED", "Loan liquidated"),
                    ("LOAN_CLOSED", "Loan closed"),
                ],
                max_length=50,
            ),
        ),
    ]
